API 7350 fortify may 2021 docker issues
department-of-veterans-affairs/lighthouse-oauth-proxy pull request #15
Opened 2021-06-04 14:49 UTC by crolarlibertyva

- Addresses fortify findings regarding ROOT user or not specifying a USER  in the dockerfile

2021-06-07 13:18 UTC, duganth-va reviewed
This looks good to me! Since we are doing everything as Node user we could clean up the file by removing the `USER node` statements throughout.

It might be a good time to remove the old Dockerfile and transition DockerfileFG to the standard Dockerfile.

2021-06-07 13:18 UTC, duganth-va commented on oauth-proxy/Dockerfile
>  USER node
😄  We can remove these user statements now

2021-06-07 13:37 UTC, crolarlibertyva commented
> This looks good to me! Since we are doing everything as Node user we could clean up the file by removing the `USER node` statements throughout.
> 
> It might be a good time to remove the old Dockerfile and transition DockerfileFG to the standard Dockerfile.

I was thinking the same thing!!

2021-06-07 15:07 UTC, crolarlibertyva commented on oauth-proxy/Dockerfile
>  USER node
fortify is dinging us again on default user privilege.  I'll put the USER back to pacify the fortify scan.

2021-06-07 20:40 UTC, dbrown-va requested changes

2021-06-07 20:40 UTC, dbrown-va commented on oauth-proxy/Dockerfile
> +COPY ./fwdproxy.crt ./fwdproxy.crt
This copy fails to run locally.

Since it isn't used locally, would recommend removing.  The future combing of Dockerfile and DockefileFG can explore making that an optional parameter.

2021-06-07 20:45 UTC, beaugrantham-va commented on oauth-proxy/DockerfileFG
> +from vasdvp/lighthouse-node-application-base:node12
Updating docker-compose.yml with `dockerfile: oauth-proxy/DockerfileFG` works locally.

Since the only difference is labels (which don't matter for local dev) and the CMD (which is overridden by docker-compose) I think it's safe to pick/drop one or the other of these?

I'll approve the PR either way, in case you want to justify doing this extra work in a new story.

2021-06-07 21:10 UTC, beaugrantham-va commented on oauth-proxy/DockerfileFG
> +from vasdvp/lighthouse-node-application-base:node12
Nevermind on the comment above. It sounds like there are behavior differences with different versions of docker. I think we stick with two files for now and open a new story to consolidate.

2021-06-07 21:58 UTC, dbrown-va commented on oauth-proxy/Dockerfile.bats
> +RUN useradd bats
Tried building & running this from the branch and got a permissions error.

```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=vasdvp%2Flighthouse-auth-utils&tag=latest: dial unix /var/run/docker.sock: connect: permission denied
```

2021-06-08 12:40 UTC, beaugrantham-va commented on oauth-proxy/Dockerfile.bats
> +RUN useradd bats
Same.

2021-06-09 15:19 UTC, crolarlibertyva commented on oauth-proxy/Dockerfile.bats
> +RUN useradd bats
Reverted.

2021-06-09 15:49 UTC, beaugrantham-va approved these changes

2021-06-09 15:57 UTC, merged