Launch logging api 17691
department-of-veterans-affairs/lighthouse-oauth-proxy pull request #70
Opened 2022-08-04 14:01 UTC by hncj811-va

2022-08-04 15:22 UTC, dbrown-va requested changes
Would like to see a description of the change in the PR description as well as a link to the JIRA item being worked.  Helps both the current reviewers and future-us should we look back at the changes.

2022-08-04 15:25 UTC, dbrown-va commented on src/oauthHandlers/authorizeHandler.js
> +          "function: authorizeHandler"
We are actually able to find this information based on the type of OAuth client registration for the client-id, so these function portions can be removed to simplify the changes a bit.

2022-08-04 15:35 UTC, hncj811-va commented on src/oauthHandlers/authorizeHandler.js
> +          "function: authorizeHandler"
Ok so you're saying we do not need the function name in the logging?

2022-08-04 15:36 UTC, dbrown-va commented on src/utils.js
> +    // decaprecated launch condition
Small typo introduced here.

2022-08-04 15:37 UTC, dbrown-va commented on src/utils.js
> -/**
This javadoc should be enhanced to include information about the logger & client_id rather than removed.

2022-08-04 15:48 UTC, dbrown-va commented on src/utils.js
> +      `${funcname} Client: ${client_id} using deprecated launch style. Launch below: \n ${launch}`
Since the `launch` value contains the patient ICN in most cases it is probably best to omit.  The offending client is the item needed.

A simplified logger would look something like `logger.warn("Client: ${client_id} using deprecated launch style.);`

2022-08-04 16:44 UTC, hncj811-va commented on src/utils.js
> -/**
pushed

2022-08-04 17:08 UTC, crolarlibertyva commented
Some UT's failing for me.

2022-08-04 17:10 UTC, dbrown-va commented on tests/utils.test.js
> +      "Client: 0oabj7zb3yUvv3iUJ2p7 using deprecated launch style. Launch below: \n 1234V5678"
This log message will need to be updated to no longer include the trailing `Launch below: \n 1234V5678`

2022-08-05 13:50 UTC, hncj811-va commented
Log client id's for clients using CCG with deprecated launch/* scope and non-Base64 encoded launch payload.

https://vajira.max.gov/browse/API-17691

2022-08-05 18:28 UTC, dbrown-va approved these changes

2022-08-05 18:28 UTC, merged